version: 2.1

aliases:
  - &workspace_root /go/src/github.com/t3n/elastic-health
  - &save_go_mod
    key: go-mod-{{ .Branch }}-{{ checksum "go.sum" }}
    paths:
      - /go/pkg/mod
  - &restore_go_mod
    keys:
      - go-mod-{{ .Branch }}-{{ checksum "go.sum" }}
      - go-mod-{{ .Branch }}-
      - go-mod-
  - &persist_to_workspace
    root: *workspace_root
    paths:
      - build
      - Dockerfile
  - &attach_workspace
     at: *workspace_root

orbs:
  docker-image: t3n/docker-image@1.0

jobs:
  test:
    working_directory: *workspace_root
    docker:
      - image: circleci/golang:1.13
        environment:
          GO111MODULE: "on"
    steps:
      - checkout
      - restore_cache: *restore_go_mod
      - run:
          name: Run tests
          command: go test -v
      - save_cache: *save_go_mod
  build:
    working_directory: *workspace_root
    docker:
      - image: circleci/golang:1.13
        environment:
          GO111MODULE: "on"
          CGO_ENABLED: "0"
    steps:
      - checkout
      - restore_cache: *restore_go_mod
      - run:
          name: Build
          command: go build -a -o build/elastic-health main.go
      - persist_to_workspace: *persist_to_workspace
  docker_build_and_push:
    working_directory: *workspace_root
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace: *attach_workspace
      - setup_remote_docker
      - docker-image/gcr-build-and-push:
          image: elastic-health
  docker_build_and_push_tag:
    working_directory: *workspace_root
    docker:
      - image: google/cloud-sdk
    steps:
      - attach_workspace: *attach_workspace
      - setup_remote_docker
      - docker-image/gcr-build-and-push-tag:
          image: elastic-health

workflows:
  version: 2
  build_and_push:
    jobs:
      - test
      - build:
          filters:
            branches:
              only:
                - master
          requires:
            - test
      - docker_build_and_push:
          filters:
            branches:
              only:
                - master
          context: google
          requires:
            - build
